/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.uddl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UddlRuntimeModule extends AbstractUddlRuntimeModule {
}
