/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.uddl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UddlUiModule extends AbstractUddlUiModule {

	public UddlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
