/*
 * generated by Xtext 2.28.0
 */
package com.epistimis.uddl.formatting2;

import com.epistimis.uddl.uddl.ConceptualDataModel;
import com.epistimis.uddl.uddl.ConceptualElement;
import com.epistimis.uddl.uddl.DataModel;
import com.epistimis.uddl.uddl.LogicalDataModel;
import com.epistimis.uddl.uddl.PlatformDataModel;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;

public class UddlFormatter extends AbstractJavaFormatter {

	protected void format(DataModel dataModel, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (ConceptualDataModel conceptualDataModel : dataModel.getCdm()) {
			doc.format(conceptualDataModel);
		}
		for (LogicalDataModel logicalDataModel : dataModel.getLdm()) {
			doc.format(logicalDataModel);
		}
		for (PlatformDataModel platformDataModel : dataModel.getPdm()) {
			doc.format(platformDataModel);
		}
	}

	protected void format(ConceptualDataModel conceptualDataModel, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (ConceptualElement conceptualElement : conceptualDataModel.getElement()) {
			doc.format(conceptualElement);
		}
		for (ConceptualDataModel _conceptualDataModel : conceptualDataModel.getCdm()) {
			doc.format(_conceptualDataModel);
		}
	}
	
	// TODO: implement for LogicalDataModel, PlatformDataModel, ConceptualEntity, ConceptualAssociation, ConceptualParticipant, ConceptualParticipantPathNode, ConceptualCharacteristicPathNode, ConceptualCompositeQuery, LogicalMeasurementSystem, LogicalMeasurementSystemAxis, LogicalReferencePoint, LogicalValueTypeUnit, LogicalMeasurement, LogicalEntity, LogicalAssociation, LogicalParticipant, LogicalParticipantPathNode, LogicalCharacteristicPathNode, LogicalCompositeQuery, PlatformStruct, PlatformEntity, PlatformAssociation, PlatformParticipant, PlatformParticipantPathNode, PlatformCharacteristicPathNode, PlatformCompositeQuery
}
